import "./singleArticle.css"

export default function SingleArticle(){
    return (
        <div className="single-article">
            <article className="article">
                <div className="headline">
                    <h1 className="h1">Lorem Ipsum</h1>
                    <span>Author: <b>Author Name</b></span>
                </div>
                <img src="./Asset/22.jpg" alt=""/>
                <p className="p">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo sint vel ab saepe provident suscipit quasi non distinctio? Iure eos neque libero eaque iusto officiis rerum commodi fugiat? Incidunt, id asperiores ratione numquam cumque tempora at exercitationem. Beatae pariatur cumque accusantium quo soluta praesentium, accusamus sit ipsum ullam ab aspernatur odit. Possimus earum quidem temporibus optio laborum dolor quod ad quas. Soluta modi debitis tenetur porro provident omnis quae placeat optio voluptatem, odit excepturi eaque vel sit error temporibus quia eum asperiores sint nisi perspiciatis. Est, nemo laudantium optio, facilis ratione nam nisi odio velit vel illum impedit eveniet atque repellendus reiciendis neque fuga voluptatem et! Qui, mollitia? Tenetur aliquam ea facilis, laudantium eos eaque tempora molestias minima dolorem adipisci quibusdam odit reiciendis nihil corrupti debitis quae facere assumenda, animi perspiciatis. Accusantium saepe ab aut alias, veritatis odit? Optio illo inventore tempore vero natus voluptatum in quae nemo iste minima quasi alias, at nostrum non itaque mollitia beatae. Reprehenderit, esse. Eligendi blanditiis odio dolores quis ut repellendus excepturi repellat temporibus! Voluptatibus omnis dicta aperiam dolore, magnam iste autem quis consequuntur eius commodi unde labore animi adipisci dolorum. Placeat non eveniet pariatur iure, consequatur facere sed! Modi quaerat assumenda voluptatem aperiam.</p>
                <p className="p">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus reiciendis nulla modi ad harum vitae doloremque sed, debitis, asperiores incidunt ex consectetur in dignissimos? Ut voluptate esse asperiores ullam maiores repellat? Quibusdam doloribus ipsum mollitia fuga, sit quo nostrum, sint distinctio, necessitatibus deleniti eos totam error sunt officiis. Reiciendis ratione nostrum fugit quia earum! Beatae voluptate iusto voluptatum corporis saepe facere architecto ratione? Vel voluptatibus fugit, recusandae facere quaerat similique aliquam corrupti quasi ipsam. Rem ad voluptatem ullam quod placeat dignissimos ipsum, architecto labore nesciunt modi, corrupti earum tenetur nulla beatae fuga tempora? Repellendus sunt nesciunt nobis neque nemo facere?</p>
                <p className="p">Lorem ipsum dolor sit amet consectetur adipisicing elit. Id unde perspiciatis error maxime praesentium inventore, modi dignissimos omnis repudiandae facilis veritatis molestiae eligendi, dolor amet sunt vel quis fugiat obcaecati consequuntur nisi. Ipsam quidem nihil repellat quaerat atque. Perspiciatis recusandae sunt architecto optio? Aliquam blanditiis sit molestiae, culpa minima dolor asperiores cupiditate ullam nulla rem delectus voluptate eveniet veniam quidem reiciendis id magnam eos fugiat totam a voluptas sint quam hic quod. Vitae provident delectus odio magnam debitis sapiente tempore sequi dolore, ullam optio qui rem molestias ut fugit consequuntur quos repellendus deleniti neque voluptatem labore similique pariatur. Libero, iusto?</p>
                <p className="p">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore, cumque cupiditate. Sit delectus earum nihil perspiciatis sint quibusdam sapiente molestias optio ratione repellendus velit tenetur porro, magnam mollitia laudantium corrupti odio inventore. Culpa harum id quo libero et vitae rem quaerat assumenda corporis! Et aut nemo itaque recusandae in beatae vero numquam excepturi magnam autem iure quo incidunt provident accusamus consequuntur, dolore fuga unde. Cupiditate tempora repellendus quibusdam illo autem eaque sed quam quod, magnam fugit sapiente expedita non, molestiae magni exercitationem dolores. Fugiat sit ipsum quaerat ipsa quis assumenda, dolores sequi libero, iusto laborum alias corporis saepe, nobis praesentium dignissimos doloribus rem ad animi asperiores nulla cum sint quod voluptas perferendis. Placeat voluptatum quis dolor voluptatibus alias pariatur quam. Nostrum repellat tempora doloribus minima, similique veniam quas tenetur eum voluptates debitis animi blanditiis esse cumque atque optio unde id obcaecati, dolor eius eligendi iste. Perferendis, error non. Eum doloremque voluptas, a accusamus fuga voluptatem, at soluta qui hic minus mollitia maiores dignissimos. Debitis perspiciatis impedit dolor quod quas? Odit voluptatibus nostrum, quos neque qui suscipit voluptatum a sequi magni provident asperiores accusantium excepturi illum facere totam tenetur natus obcaecati id eligendi laboriosam! Nobis eius quae commodi tenetur nihil optio.</p>
                <p className="p">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aliquam deserunt magnam delectus cumque cupiditate assumenda itaque voluptates incidunt ullam error aspernatur ipsam ab ad at ea, et beatae, alias maxime impedit fuga consequuntur! Corrupti praesentium atque hic veritatis ratione quam animi culpa qui perferendis, cum molestias exercitationem maiores vitae neque necessitatibus quae vel non iste ipsum. Dolore exercitationem fugit vero architecto, at veniam accusantium nam corporis rem praesentium tempora commodi beatae soluta cupiditate, quaerat, consequatur nobis eligendi quasi. Est sed provident quas quisquam voluptate molestias fuga, a repellendus quia, mollitia veritatis repudiandae impedit obcaecati sunt? Eius ratione itaque accusamus ipsam.</p>
            </article>
        </div>
    )
}
